language: node_js
node_js:
  - "0.11.13"
  - "0.10"
install:
  - sudo apt-get update
  - sudo apt-get install libc6:i386 libstdc++6:i386
  - build/install_sdk.sh
  - third_party/clang/download_python_bindings.py
  - npm install
  - export CHROME_URL=https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64
  - export CHROME_REV=$(curl -s ${CHROME_URL}/LAST_CHANGE)
  - curl ${CHROME_URL}/${CHROME_REV}/chrome-linux.zip --create-dirs -o out/chrome-linux.zip
  - unzip out/chrome-linux.zip -d out
before_script:
  - export CHROME_BIN=$PWD/out/chrome-linux/chrome
  - export DISPLAY=:99.0
  - export NACL_SDK_ROOT=$PWD/out/nacl_sdk/pepper_canary
  - sh -e /etc/init.d/xvfb start
script:
  - npm test
  - ./integration_tests.sh
